### ISSUE TITLE
Maps extraction container exiting with code 139

### ISSUE THREAD

**Issue by EthanBlackburn** [wowstack/docker-classic-server#1]
I modified the docker-compose.yaml file to mount my local wow directory. When I run the maps_extractors container, it repeatedly restarts with code 139:

```
map_extractors_1  | Welcome to the WowStack classic-server container
map_extractors_1  | Subscribe to project updates by watching https://github.com/wowstack/docker-classic-server
map_extractors_1  | Submit issues and feature requests at https://github.com/wowstack/docker-classic-server/issues
map_extractors_1  | Send us your feedback at support@wowstack.io
map_extractors_1  | 
map_extractors_1  | INFO  ==> Starting data extraction...
map_extractors_1  | INFO  ==> Checking directories in /opt/wowstack/share/...
map_extractors_1  | INFO  ==> Buildings missing...
map_extractors_1  | INFO  ==> Cameras missing...
map_extractors_1  | INFO  ==> DBCs missing...
map_extractors_1  | INFO  ==> Maps missing...
map_extractors_1  | INFO  ==> Height maps missing...
map_extractors_1  | INFO  ==> Movement maps missing...
map_extractors_1  | INFO  ==> Removing old extracted data...
map_extractors_1  | INFO  ==> Extracting cameras, DBCs and maps...
dockerclassicservermaster_map_extractors_1 exited with code 139
```

I have wow client 1.12.1 FWIW

**Comment by danielsreichenbach** [comment]
Thanks for the report! Any version of WoW 1.12 is fine. Stumbled over the issue myself and am currently working on a fix.

**Comment by danielsreichenbach** [comment]
@EthanBlackburn it seems the the error was on my side. Inside the entry point, I was calling `exec` inside the shell script to fork a process of any of the map tools like this

```bash
$WOWSTACK_PREFIX/bin/map-extractor "-f 0 -i $WOWSTACK_PREFIX/data"
```

Instead of passing the parameters to the extractor as multiple parameters it just did pass one parameter as `argv` to the main function, instead of the expected multiple parameters.

The fix was to call it like this:

```bash
$WOWSTACK_PREFIX/bin/map-extractor "-f" "0" "-i" "$WOWSTACK_PREFIX/data"
```

... and suddenly we get the expected amount of parameters into `argv`.

Pushing a updated container now.
